#4  &  #8
ShanghaitechGeekPie/coursebench-backend pull request #16
Opened 2024-04-08 14:01 UTC by kuangpenghao

2024-04-09 10:15 UTC, Prince213 requested changes
Things to improve:
- [ ] Change pull request title
- [ ] Use proper commit messages.

2024-04-09 10:15 UTC, Prince213 commented on pkg/queries/user.go
Move these lines up to the invitation code check block.

2024-04-09 10:15 UTC, Prince213 commented on pkg/models/user.go
> +	Reward           int  `gorm:"default:0"`
No need to set default value here, it's already the default.

```suggestion
	Reward           int
```

2024-04-09 10:15 UTC, Prince213 commented on pkg/models/comment.go
> +	Reward			    int  `gorm:"default:0"`
No need to set default value here, it's already the default.

```suggestion
	Reward			    int
```

2024-04-09 10:15 UTC, Prince213 commented on internal/controllers/comments/user.go
> +		}
Always format your code before submitting.

2024-04-09 10:15 UTC, Prince213 commented on pkg/models/user.go
> +	InvCanReward   	 bool  `gorm:"default:false"`
Avoid bad abbreviation. Also its purpose is not obvious by looking at the name.

2024-04-09 11:58 UTC, AstatineAi requested changes

2024-04-09 11:58 UTC, AstatineAi commented on pkg/queries/user.go
> +	if u.InvitationCode != ""{
`u.InvitationCode` is the invitation code generated in the current function for the registered user, not someone else's invitation code that the new user used to register. Use the `invitation_code` parameter of this function.

2024-04-09 11:58 UTC, AstatineAi commented on pkg/queries/user.go
> +		userInvite.Reward += 1
`1` represents 0.01 yuan, please refer to the docs.

2024-04-16 12:15 UTC, WAAutoMaton commented on internal/controllers/comments/user.go
1. 计算 reward 的代码不应该放在 GenerateResponse 方法内（功能和方法名字不符）。我的建议是写在 `comments/Post` 方法内。
2. 对 User 示例修改后需要调用 `Save` 保存，否则修改不会写入数据库。
3. 获得 reward 的应该是邀请该用户的用户，而不是发表评论的用户自身
4. 整个修改过程应该用事务包起来，并且应该和发表评论作为同一个事务，建议是写在  `comments/post.go:106` 中 ：

```go
// 插入评论作为一个事务，若插入失败则回滚
err = db.Transaction(func(tx *gorm.DB) error {
	...
}
```

2024-04-16 12:50 UTC, WAAutoMaton commented on pkg/queries/user.go
这部分代码更适合放在 register_active 的逻辑中

此外这部分也应该使用事务包起来

2024-04-26 13:29 UTC, closed without merging

2024-04-26 13:29 UTC, Prince213 commented
Closing due to no activity.